version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  sonar-scanner: nodis-com-br/sonar-scanner@0.1.0

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      
