version: 2.1
description: "This orb measures code quality using SonarQube server and fails the build when the predefined quality gate has broken. Default sonarScanner is used to execute analysis. The script runs with zero tolerancy in terms of errors. If any error found during the analysis the build will fail."
commands:
  check-code-quality:
    description: Check Code Quality
    parameters:
        sonar_server_url:
            type: string
            description: "URL of your SonarQube server. e.g.: http://localhost:9000"
            default: "$SONAR_SERVER"
        sonar_login:
            description: "Authentication key (sonar.login paramter) to access SonarQube and perform analysis"
            type: string
            default: "$SONAR_TOKEN"
    
job:
  steps:
   
    - run: mvn test
    - run:
        name: Run Sonarscanner
        command: |
            export SONAR_SCANNER_OPTS="-Xmx2048m"
            eval ./sonar-scanner-4.2.0.1873/bin/sonar-scanner -Dsonar.host.url= http://localhost:9000 \
            -Dsonar.login=admin/admin