jobs:
  build:
    steps:
      - checkout
      - sonarcloud/scan
       - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar
        - run: 
          command: mvn package

orbs:
  sonarcloud: admin/admin
version: 2.1
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud