version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: mvn package
      - sonarcloud/scan_with_maven
      - run:
           name: Run Sonarqube scanner
           command: |
            export SONARQUBE_TOKEN=05edd31dfe9ec516beefe3d341eeae24bf2ea51f
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.projectVersion=0.9.4 \
            -Dsonar.login=admin \
            -Dsonar.password=admin